version: "3.8"


services:

  db:
    image: postgres
    enviroment:
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data


  app:
    build: ./app
    dependence:
      - db
    ports:
      -"5000:5000"

volumes:
  db_data:
